vault:
  base_path: "~/notes/"
  
  directories:
    content: "areas/personal-brand/website/"
    dailies: "dailies" 
    financial: "areas/finance/"
    metrics: "metrics"
    anki: "anki"
    blog: "areas/personal-brand/posts/blog"
    thoughts: "capture/raw_capture"
    books: "resources/books"
    events: "events"
    principles: "areas/principles"

database:
  path: "database/website.db"

