vault:
  base_path: "~/notes/"
  
  directories:
    content: "~/notes/areas/personal-brand/website/"
    dailies: "dailies" 
    financial: "areas/finance/"
    metrics: "metrics"
    anki: "anki"
    blog: "areas/personal-brand/blog"
    thoughts: "capture/raw_capture"

database:
  path: "database/website.db"
