vault:
  base_path: "mock-obsidian/"
  
  directories:
    content: "content/"
    dailies: "dailies" 
    financial: "financial/"
    metrics: "metrics"
    anki: "anki"
    blog: "content/"
    thoughts: "notes/capture/raw_capture"
    books: "notes/resources/books"
    events: "events"

database:
  path: "database/website.db"

